<?php

namespace JS\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GaleriaItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaItemRepository extends EntityRepository
{
}
