<?php

namespace JS\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends EntityRepository
{
    public function getGalerias(){
        $qb = $this->createQueryBuilder('G')
            ->select('G', 'I')
            ->leftJoin('G.items','I')
            ->orderBy('G.posicion')
            ->addOrderBy('I.posicion');

        return $qb->getQuery()->getResult();
    }
}
