<?php

namespace JS\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PredicaDevocionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredicaDevocionalRepository extends EntityRepository
{
}
