services:
    JS.sontaextends.extendsblock:
        id: JS.sontaextends.extendsblock
        class: JS\SonataExtendsBundle\Block\ExtendsBlockService
        arguments:
            - @service_container
            - JS.sontaextends.extendsblock
            - @templating
        tags:
            - { name: sonata.block }
            
    sonata.admin.JS.extends.base:
        class: JS\SonataExtendsBundle\Admin\FakeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "JSExtendsBaseAdmin", label: "JSExtendsBaseAdmin" }
        arguments:
            - ~
            - JS\SonataExtendsBundle\Entity\FakeEntity
            - ~
        calls:
            - [ setTranslationDomain, [JSSonataExtendsBundle]]
            
